language: python
python:
  - 2.7
  - 3.6

install:
  - pip install pip --upgrade
  - pip install setuptools --upgrade
  - pip install -r tests/requirements.txt
  - pip install -r requirements.txt
  - python setup.py install

script: 
  - flake8 .
  - python -m nose tests --with-coverage --cover-package tes --cover-min-percentage 80

after_success:
  - coveralls

notifications:
  email: false
